#ifndef DEFINES_H
#define DEFINES_H

#define MQTT_CUSTOMER "viktak"
#define MQTT_PROJECT  "spiti"

#define HARDWARE_ID "Hall sensors"
#define HARDWARE_VERSION "1.0"
#define SOFTWARE_ID "Hall"
#define FIRMWARE_VERSION "1.4"

#define JSON_SETTINGS_SIZE (JSON_OBJECT_SIZE(10) + 200)
#define JSON_MQTT_COMMAND_SIZE 300

#define CONNECTION_STATUS_LED_GPIO 0
#define ONE_WIRE_BUS 2
#define DS1820_RESOLUTION 12
#define PIR_GPIO   4

#define DEFAULT_TEMPERATURE_REFRESH_INTERVAL 120
#define DEFAULT_HEARTBEAT_INTERVAL 300

#endif